version: '3.9'
services:
  web:
    build: .
    ports:
      - "8443:80"
    depends_on:
      - database
  database:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: pomelo_db
      MYSQL_ROOT_PASSWORD: "pomelo"